name: Automatic Deployment

on:
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Welcome
        run: echo Start deploying SenOS
      - name: Build Dockerfile
        run: |
          sed -i 's/__ENV__/stag/g' Dockerfile
          cat Dockerfile
      - name: Build docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesnetwork/senos
          tags: devnet
      - name: Run docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATEKEY_STAGING }}
          script: |
            sudo docker stop senos
            sudo docker rm senos
            sudo docker pull descartesnetwork/senos:devnet
            sudo docker run -d -p 80:80 --name senos descartesnetwork/senos:devnet
            sudo docker image prune -a -f
